# Generated by Django 4.2.11 on 2026-07-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_password_alter_usuario_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ingeniería de Sistemas, Ingeniería Ambiental', max_length=200)),
                ('codigo', models.CharField(help_text='Código único de la escuela (Ej: IS, IA, IM)', max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la escuela está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('presidente', models.ForeignKey(blank=True, help_text='Presidente de esta escuela', limit_choices_to={'tipo_usuario': 'presidente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuela_presidida', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Escuela Profesional',
                'verbose_name_plural': 'Escuelas Profesionales',
                'db_table': 'escuela',
                'ordering': ['nombre'],
            },
        ),
    ]
