# Generated by Django 4.2.11 on 2026-07-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_usuario_activo_usuario_email_and_more'),
        ('informes', '0003_alter_informe_options_informe_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuevo_informe', 'Nuevo Informe Recibido'), ('asignado_presidente', 'Informe Asignado a Presidente'), ('asignado_docente', 'Informe Asignado a Docente'), ('revision_completa', 'Revisión Completada'), ('aprobado_presidente', 'Aprobado por Presidente'), ('rechazado_presidente', 'Rechazado por Presidente'), ('aprobado_final', 'Informe Aprobado - Proceso Completo'), ('rechazado_estudiante', 'Informe Rechazado - Requiere Correcciones')], help_text='Tipo de notificación', max_length=50)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=255)),
                ('mensaje', models.TextField(help_text='Mensaje completo de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Si el usuario ya leyó la notificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('informe', models.ForeignKey(help_text='Informe relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='informes.informe')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
