# Generated by Django 5.0.6 on 2026-06-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_usuario', models.CharField(choices=[('estudiante', 'Estudiante'), ('egresado', 'Egresado')], default='estudiante', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
