# Generated by Django 4.2.11 on 2026-07-08 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
        ('usuarios', '0002_usuario_password_alter_usuario_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['tipo_usuario', 'nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el usuario está activo en el sistema'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para notificaciones', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escuela',
            field=models.ForeignKey(blank=True, help_text='Escuela a la que pertenece (estudiantes, docentes, presidente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='escuelas.escuela'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(help_text='Código único del usuario', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('egresado', 'Egresado'), ('docente', 'Docente'), ('presidente', 'Presidente de Escuela'), ('secretaria', 'Secretaria Académica')], default='estudiante', max_length=20),
        ),
    ]
