# Generated by Django 5.0.6 on 2026-06-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reglamento',
            },
        ),
    ]
