# Generated by Django 4.2.11 on 2026-07-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_usuario_activo_usuario_email_and_more'),
        ('observaciones', '0003_bancoobservacionesdocente'),
        ('escuelas', '0001_initial'),
        ('informes', '0002_informe_comentario_docente_informe_docente_revisor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Informe de Práctica', 'verbose_name_plural': 'Informes de Práctica'},
        ),
        migrations.AddField(
            model_name='informe',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo PDF o DOCX del informe', null=True, upload_to='informes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='informe',
            name='banco_observaciones_usado',
            field=models.ForeignKey(blank=True, help_text='Banco de observaciones que usó el docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_validados', to='observaciones.bancoobservacionesdocente'),
        ),
        migrations.AddField(
            model_name='informe',
            name='comentario_presidente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='comentario_secretaria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='escuela',
            field=models.ForeignKey(blank=True, help_text='Escuela profesional del estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='escuelas.escuela'),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_aprobacion_presidente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_asignacion_docente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_asignacion_presidente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_asignacion_secretaria',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='presidente_asignado',
            field=models.ForeignKey(blank=True, help_text='Presidente de escuela asignado', limit_choices_to={'tipo_usuario': 'presidente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_presidente', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='informe',
            name='secretaria_asignada',
            field=models.ForeignKey(blank=True, help_text='Secretaria que procesó el informe', limit_choices_to={'tipo_usuario': 'secretaria'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_secretaria', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='contenido',
            field=models.TextField(help_text='Texto extraído del archivo'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='docente_revisor',
            field=models.ForeignKey(blank=True, help_text='Docente revisor asignado', limit_choices_to={'tipo_usuario': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_docente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado por Estudiante'), ('pendiente_secretaria', 'Pendiente - Secretaría'), ('pendiente_presidente', 'Pendiente - Presidente'), ('pendiente_docente', 'Pendiente - Docente Asignado'), ('validando_ia', 'Validando con IA'), ('revision_docente', 'En Revisión del Docente'), ('pendiente_aprobacion_presidente', 'Pendiente Aprobación Presidente'), ('aprobado_presidente', 'Aprobado por Presidente'), ('rechazado_presidente', 'Rechazado por Presidente'), ('aprobado_final', 'APROBADO FINAL'), ('rechazado_estudiante', 'Rechazado - Estudiante debe Corregir'), ('validando', 'Validando con IA (deprecado)'), ('observado', 'Con Observaciones (deprecado)'), ('rechazado', 'Rechazado (deprecado)'), ('aprobado', 'Aprobado (deprecado)'), ('completado', 'Completado (deprecado)')], default='enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(help_text='Estudiante que envió el informe', on_delete=django.db.models.deletion.CASCADE, related_name='informes_enviados', to='usuarios.usuario'),
        ),
    ]
