# Generated by Django 5.0.6 on 2026-06-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciongenerada',
            name='comentario_docente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observaciongenerada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('confirmada', 'Confirmada por Docente'), ('descartada', 'Descartada por Docente'), ('corregida', 'Corregida por Alumno')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='observaciongenerada',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observaciongenerada',
            name='severidad',
            field=models.CharField(choices=[('critica', 'Crítica - Debe Corregirse'), ('importante', 'Importante'), ('menor', 'Menor'), ('sugerencia', 'Sugerencia')], default='importante', max_length=20),
        ),
    ]
