# Generated by Django 4.2.11 on 2026-07-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_usuario_activo_usuario_email_and_more'),
        ('observaciones', '0002_observaciongenerada_comentario_docente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoObservacionesDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del banco (Ej: Observaciones 2026-1)', max_length=255)),
                ('archivo', models.FileField(help_text='Archivo PDF o DOCX con observaciones', upload_to='bancos_observaciones/%Y/%m/')),
                ('contenido_extraido', models.TextField(blank=True, help_text='Texto extraído del archivo para usar con IA')),
                ('activo', models.BooleanField(default=True, help_text='Si este banco está activo (solo uno activo por docente)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(help_text='Docente propietario de este banco', limit_choices_to={'tipo_usuario': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='bancos_observaciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Banco de Observaciones del Docente',
                'verbose_name_plural': 'Bancos de Observaciones de Docentes',
                'db_table': 'banco_observaciones_docente',
                'ordering': ['-activo', '-fecha_creacion'],
                'unique_together': {('docente', 'nombre')},
            },
        ),
    ]
