version: '3.9'
services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: untels_db
      POSTGRES_USER: untels_user
      POSTGRES_PASSWORD: untels_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: django-app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://untels_user:untels_pass@db:5432/untels_db
    depends_on:
      - db
volumes:
  postgres_data:
