# Generated by Django 5.0.6 on 2026-06-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
        ('usuarios', '0002_usuario_password_alter_usuario_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='comentario_docente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='docente_revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_revisados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_revision_docente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='informe_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_posteriores', to='informes.informe'),
        ),
        migrations.AddField(
            model_name='informe',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='informe',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('validando', 'Validando con IA'), ('observado', 'Con Observaciones'), ('revision_docente', 'En Revisión del Docente'), ('rechazado', 'Rechazado - Requiere Correcciones'), ('aprobado', 'Aprobado por Docente'), ('completado', 'Completado')], default='enviado', max_length=30),
        ),
    ]
