# Generated by Django 5.0.6 on 2026-06-17 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoObservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'banco_observaciones',
            },
        ),
        migrations.CreateModel(
            name='ObservacionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('ubicacion_error', models.CharField(max_length=255)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='informes.informe')),
            ],
            options={
                'db_table': 'observacion_generada',
            },
        ),
    ]
